/**
 * HTML生成サービス
 * プロジェクト解析結果からスタンドアロンHTMLを生成する
 */
import type {
  CharacterSummary,
  ManuscriptSummary,
  ProjectAnalysis,
  SettingSummary,
} from "./project_analyzer.ts";

/**
 * HTML生成クラス
 */
export class HtmlGenerator {
  /**
   * プロジェクト解析結果からHTMLを生成
   */
  generate(analysis: ProjectAnalysis): string {
    const charactersSection = this.renderCharacters(analysis.characters);
    const settingsSection = this.renderSettings(analysis.settings);
    const manuscriptsSection = this.renderManuscripts(analysis.manuscripts);

    return `<!DOCTYPE html>
<html lang="ja">
<head>
  <meta charset="UTF-8">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <title>Story Project Overview</title>
  <style>
${CSS_STYLES}
  </style>
</head>
<body>
  <div class="container">
    <header>
      <h1>Story Project Overview</h1>
    </header>

    <main>
      <section class="characters">
        <h2>Characters</h2>
        ${charactersSection}
      </section>

      <section class="settings">
        <h2>Settings</h2>
        ${settingsSection}
      </section>

      <section class="manuscripts">
        <h2>Manuscripts</h2>
        ${manuscriptsSection}
      </section>
    </main>

    <footer>
      <p>Generated by storyteller</p>
    </footer>
  </div>
</body>
</html>`;
  }

  /**
   * キャラクターセクションをレンダリング
   */
  private renderCharacters(characters: readonly CharacterSummary[]): string {
    if (characters.length === 0) {
      return '<p class="empty">No characters found.</p>';
    }

    const cards = characters.map((char) => `
        <div class="card character-card">
          <h3>${escapeHtml(char.name)}</h3>
          <div class="meta">
            <span class="role">${escapeHtml(char.role ?? "unknown")}</span>
            <span class="id">${escapeHtml(char.id)}</span>
          </div>
          <p class="summary">${escapeHtml(char.summary ?? "")}</p>
          <div class="display-names">
            <span class="label">Names:</span>
            ${
      char.displayNames.map((n) => `<span class="tag">${escapeHtml(n)}</span>`)
        .join(" ")
    }
          </div>
          <div class="file-path">
            <code>${escapeHtml(char.filePath)}</code>
          </div>
        </div>`).join("\n");

    return `<div class="card-grid">${cards}</div>`;
  }

  /**
   * 設定セクションをレンダリング
   */
  private renderSettings(settings: readonly SettingSummary[]): string {
    if (settings.length === 0) {
      return '<p class="empty">No settings found.</p>';
    }

    const cards = settings.map((setting) => `
        <div class="card setting-card">
          <h3>${escapeHtml(setting.name)}</h3>
          <div class="meta">
            <span class="id">${escapeHtml(setting.id)}</span>
          </div>
          <p class="summary">${escapeHtml(setting.summary ?? "")}</p>
          <div class="display-names">
            <span class="label">Names:</span>
            ${
      setting.displayNames.map((n) =>
        `<span class="tag">${escapeHtml(n)}</span>`
      ).join(" ")
    }
          </div>
          <div class="file-path">
            <code>${escapeHtml(setting.filePath)}</code>
          </div>
        </div>`).join("\n");

    return `<div class="card-grid">${cards}</div>`;
  }

  /**
   * 原稿セクションをレンダリング
   */
  private renderManuscripts(manuscripts: readonly ManuscriptSummary[]): string {
    if (manuscripts.length === 0) {
      return '<p class="empty">No manuscripts found.</p>';
    }

    const items = manuscripts.map((ms) => `
        <div class="manuscript-item">
          <div class="manuscript-header">
            <h3>${escapeHtml(ms.title ?? ms.path)}</h3>
            <code class="path">${escapeHtml(ms.path)}</code>
          </div>
          <div class="references">
            <span class="label">References:</span>
            ${this.renderReferences(ms.referencedEntities)}
          </div>
        </div>`).join("\n");

    return `<div class="manuscript-list">${items}</div>`;
  }

  /**
   * エンティティ参照をレンダリング
   */
  private renderReferences(
    refs: readonly { id: string; kind: string; occurrences: number }[],
  ): string {
    if (refs.length === 0) {
      return '<span class="no-refs">None</span>';
    }

    return refs.map((ref) =>
      `<span class="ref ${escapeHtml(ref.kind)}">${
        escapeHtml(ref.id)
      } (${ref.occurrences})</span>`
    ).join(" ");
  }
}

/**
 * HTMLをエスケープ
 */
function escapeHtml(text: string): string {
  return text
    .replace(/&/g, "&amp;")
    .replace(/</g, "&lt;")
    .replace(/>/g, "&gt;")
    .replace(/"/g, "&quot;")
    .replace(/'/g, "&#039;");
}

/**
 * インラインCSS
 */
const CSS_STYLES = `
    :root {
      --primary-color: #3498db;
      --secondary-color: #2ecc71;
      --background-color: #f5f6fa;
      --card-background: #ffffff;
      --text-color: #2c3e50;
      --border-color: #dfe6e9;
      --shadow: 0 2px 4px rgba(0,0,0,0.1);
    }

    * {
      box-sizing: border-box;
      margin: 0;
      padding: 0;
    }

    body {
      font-family: -apple-system, BlinkMacSystemFont, 'Segoe UI', Roboto, Oxygen, Ubuntu, sans-serif;
      background-color: var(--background-color);
      color: var(--text-color);
      line-height: 1.6;
    }

    .container {
      max-width: 1200px;
      margin: 0 auto;
      padding: 2rem;
    }

    header {
      text-align: center;
      margin-bottom: 2rem;
      padding-bottom: 1rem;
      border-bottom: 2px solid var(--primary-color);
    }

    header h1 {
      color: var(--primary-color);
      font-size: 2rem;
    }

    section {
      margin-bottom: 2rem;
    }

    section h2 {
      color: var(--text-color);
      font-size: 1.5rem;
      margin-bottom: 1rem;
      padding-bottom: 0.5rem;
      border-bottom: 1px solid var(--border-color);
    }

    .card-grid {
      display: grid;
      grid-template-columns: repeat(auto-fill, minmax(300px, 1fr));
      gap: 1rem;
    }

    .card {
      background: var(--card-background);
      border-radius: 8px;
      padding: 1.5rem;
      box-shadow: var(--shadow);
      transition: transform 0.2s;
    }

    .card:hover {
      transform: translateY(-2px);
    }

    .card h3 {
      color: var(--primary-color);
      margin-bottom: 0.5rem;
    }

    .card .meta {
      display: flex;
      gap: 0.5rem;
      margin-bottom: 0.5rem;
    }

    .card .role {
      background: var(--secondary-color);
      color: white;
      padding: 0.2rem 0.5rem;
      border-radius: 4px;
      font-size: 0.8rem;
    }

    .card .id {
      background: var(--border-color);
      padding: 0.2rem 0.5rem;
      border-radius: 4px;
      font-size: 0.8rem;
    }

    .card .summary {
      color: #666;
      margin-bottom: 0.5rem;
    }

    .display-names {
      margin-bottom: 0.5rem;
    }

    .display-names .label,
    .references .label {
      font-weight: bold;
      margin-right: 0.5rem;
    }

    .tag {
      background: var(--background-color);
      padding: 0.2rem 0.5rem;
      border-radius: 4px;
      font-size: 0.85rem;
      margin-right: 0.25rem;
    }

    .file-path {
      margin-top: 0.5rem;
    }

    .file-path code {
      background: var(--background-color);
      padding: 0.25rem 0.5rem;
      border-radius: 4px;
      font-size: 0.8rem;
    }

    .manuscript-list {
      display: flex;
      flex-direction: column;
      gap: 1rem;
    }

    .manuscript-item {
      background: var(--card-background);
      border-radius: 8px;
      padding: 1.5rem;
      box-shadow: var(--shadow);
    }

    .manuscript-header {
      display: flex;
      justify-content: space-between;
      align-items: center;
      margin-bottom: 0.5rem;
      flex-wrap: wrap;
      gap: 0.5rem;
    }

    .manuscript-header h3 {
      color: var(--primary-color);
    }

    .manuscript-header .path {
      background: var(--background-color);
      padding: 0.25rem 0.5rem;
      border-radius: 4px;
      font-size: 0.8rem;
    }

    .ref {
      display: inline-block;
      padding: 0.2rem 0.5rem;
      border-radius: 4px;
      font-size: 0.85rem;
      margin-right: 0.25rem;
    }

    .ref.character {
      background: #e3f2fd;
      color: #1565c0;
    }

    .ref.setting {
      background: #e8f5e9;
      color: #2e7d32;
    }

    .empty {
      color: #999;
      font-style: italic;
    }

    .no-refs {
      color: #999;
      font-style: italic;
    }

    footer {
      text-align: center;
      margin-top: 2rem;
      padding-top: 1rem;
      border-top: 1px solid var(--border-color);
      color: #999;
      font-size: 0.9rem;
    }
`;
