/**
 * HTML生成サービス
 * プロジェクト解析結果からスタンドアロンHTMLを生成する
 */
import type {
  CharacterSummary,
  EventSummary,
  ForeshadowingSummary,
  ManuscriptSummary,
  ProjectAnalysis,
  ResolutionSummary,
  SettingSummary,
  TimelineSummary,
} from "@storyteller/application/view/project_analyzer.ts";
import { VIS_CDN_LINKS } from "@storyteller/application/view/graph/vis_types.ts";
import {
  buildCharacterGraphFromSummary,
  buildForeshadowingGraphFromSummary,
  buildTimelineGraphFromSummary,
} from "@storyteller/application/view/graph/summary_adapters.ts";
import { ConsistencyChecker } from "@storyteller/application/view/consistency/consistency_checker.ts";
import type { ConsistencyIssue } from "@storyteller/application/view/consistency/types.ts";
import { OrphanCharacterRule } from "@storyteller/application/view/consistency/rules/orphan_character_rule.ts";
import { UnresolvedForeshadowingRule } from "@storyteller/application/view/consistency/rules/unresolved_foreshadowing_rule.ts";

/**
 * HTML生成クラス
 */
export class HtmlGenerator {
  /**
   * プロジェクト解析結果からHTMLを生成
   */
  generate(analysis: ProjectAnalysis): string {
    const charactersSection = this.renderCharacters(analysis.characters);
    const settingsSection = this.renderSettings(analysis.settings);
    const timelinesSection = this.renderTimelines(analysis.timelines);
    const foreshadowingsSection = this.renderForeshadowings(
      analysis.foreshadowings,
    );
    const manuscriptsSection = this.renderManuscripts(analysis.manuscripts);

    // グラフセクションを生成
    const characterGraphSection = this.renderCharacterGraph(
      analysis.characters,
    );
    const timelineGraphSection = this.renderTimelineGraph(analysis.timelines);
    const foreshadowingGraphSection = this.renderForeshadowingGraph(
      analysis.foreshadowings,
    );
    const graphInitScript = this.renderGraphInitScript(analysis);

    // 整合性チェック実行
    const checker = new ConsistencyChecker();
    checker.addRule(new OrphanCharacterRule());
    checker.addRule(new UnresolvedForeshadowingRule());
    const consistencyIssues = checker.check(analysis);
    const consistencySection = this.renderConsistency(consistencyIssues);

    return `<!DOCTYPE html>
<html lang="ja">
<head>
  <meta charset="UTF-8">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <title>Story Project Overview</title>
  <link rel="stylesheet" href="${VIS_CDN_LINKS.css}">
  <script src="${VIS_CDN_LINKS.network}"></script>
  <style>
${CSS_STYLES}
${GRAPH_STYLES}
${CONSISTENCY_STYLES}
  </style>
</head>
<body>
  <div class="container">
    <header>
      <h1>Story Project Overview</h1>
    </header>

    <main>
      <section class="graphs">
        <h2>Visualizations</h2>
        <div class="graph-container">
          ${characterGraphSection}
          ${timelineGraphSection}
          ${foreshadowingGraphSection}
        </div>
      </section>

      <section class="characters">
        <h2>Characters</h2>
        ${charactersSection}
      </section>

      <section class="settings">
        <h2>Settings</h2>
        ${settingsSection}
      </section>

      <section class="timelines">
        <h2>Timelines</h2>
        ${timelinesSection}
      </section>

      <section class="foreshadowings">
        <h2>Foreshadowings</h2>
        ${foreshadowingsSection}
      </section>

      <section class="manuscripts">
        <h2>Manuscripts</h2>
        ${manuscriptsSection}
      </section>

      <section class="consistency">
        <h2>整合性チェック</h2>
        ${consistencySection}
      </section>
    </main>

    <footer>
      <p>Generated by storyteller</p>
    </footer>
  </div>
  ${graphInitScript}
</body>
</html>`;
  }

  /**
   * キャラクターセクションをレンダリング
   */
  private renderCharacters(characters: readonly CharacterSummary[]): string {
    if (characters.length === 0) {
      return '<p class="empty">No characters found.</p>';
    }

    const cards = characters.map((char) => `
        <div class="card character-card">
          <h3>${escapeHtml(char.name)}</h3>
          <div class="meta">
            <span class="role">${escapeHtml(char.role ?? "unknown")}</span>
            <span class="id">${escapeHtml(char.id)}</span>
          </div>
          <p class="summary">${escapeHtml(char.summary ?? "")}</p>
          <div class="display-names">
            <span class="label">Names:</span>
            ${
      char.displayNames.map((n) => `<span class="tag">${escapeHtml(n)}</span>`)
        .join(" ")
    }
          </div>
          <div class="file-path">
            <code>${escapeHtml(char.filePath)}</code>
          </div>
        </div>`).join("\n");

    return `<div class="card-grid">${cards}</div>`;
  }

  /**
   * 設定セクションをレンダリング
   */
  private renderSettings(settings: readonly SettingSummary[]): string {
    if (settings.length === 0) {
      return '<p class="empty">No settings found.</p>';
    }

    const cards = settings.map((setting) => `
        <div class="card setting-card">
          <h3>${escapeHtml(setting.name)}</h3>
          <div class="meta">
            <span class="id">${escapeHtml(setting.id)}</span>
          </div>
          <p class="summary">${escapeHtml(setting.summary ?? "")}</p>
          <div class="display-names">
            <span class="label">Names:</span>
            ${
      setting.displayNames.map((n) =>
        `<span class="tag">${escapeHtml(n)}</span>`
      ).join(" ")
    }
          </div>
          <div class="file-path">
            <code>${escapeHtml(setting.filePath)}</code>
          </div>
        </div>`).join("\n");

    return `<div class="card-grid">${cards}</div>`;
  }

  /**
   * タイムラインセクションをレンダリング
   */
  private renderTimelines(timelines: readonly TimelineSummary[]): string {
    if (timelines.length === 0) {
      return '<p class="empty">No timelines found.</p>';
    }

    const cards = timelines.map((timeline) => `
        <div class="card timeline-card">
          <h3>${escapeHtml(timeline.name)}</h3>
          <div class="meta">
            <span class="scope">${escapeHtml(timeline.scope)}</span>
            <span class="id">${escapeHtml(timeline.id)}</span>
          </div>
          ${
      timeline.parentTimeline
        ? `<div class="parent-timeline"><span class="label">Parent:</span> ${
          escapeHtml(timeline.parentTimeline)
        }</div>`
        : ""
    }
          ${
      timeline.relatedCharacter
        ? `<div class="related-character"><span class="label">Character:</span> ${
          escapeHtml(timeline.relatedCharacter)
        }</div>`
        : ""
    }
          <p class="summary">${escapeHtml(timeline.summary ?? "")}</p>
          ${this.renderTimelineEvents(timeline.events)}
          <div class="file-path">
            <code>${escapeHtml(timeline.filePath)}</code>
          </div>
        </div>`).join("\n");

    return `<div class="timeline-list">${cards}</div>`;
  }

  /**
   * タイムラインイベントをレンダリング
   */
  private renderTimelineEvents(events: readonly EventSummary[]): string {
    if (events.length === 0) {
      return '<div class="timeline-events empty">No events.</div>';
    }

    // orderでソート
    const sortedEvents = [...events].sort((a, b) => a.order - b.order);

    const eventItems = sortedEvents.map((event) => `
      <div class="event-item">
        <div class="event-header">
          <span class="event-order">${event.order}</span>
          <span class="event-title">${escapeHtml(event.title)}</span>
          <span class="event-category">${escapeHtml(event.category)}</span>
        </div>
        <div class="event-summary">${escapeHtml(event.summary ?? "")}</div>
        ${
      event.characters.length > 0
        ? `<div class="event-refs"><span class="label">Characters:</span> ${
          event.characters.map((c) =>
            `<span class="ref character">${escapeHtml(c)}</span>`
          ).join(" ")
        }</div>`
        : ""
    }
        ${
      event.settings.length > 0
        ? `<div class="event-refs"><span class="label">Settings:</span> ${
          event.settings.map((s) =>
            `<span class="ref setting">${escapeHtml(s)}</span>`
          ).join(" ")
        }</div>`
        : ""
    }
        ${
      event.chapters.length > 0
        ? `<div class="event-refs"><span class="label">Chapters:</span> ${
          event.chapters.map((c) =>
            `<span class="ref chapter">${escapeHtml(c)}</span>`
          ).join(" ")
        }</div>`
        : ""
    }
        ${
      event.causedBy && event.causedBy.length > 0
        ? `<div class="event-causality caused-by"><span class="label">Caused by:</span> ${
          event.causedBy.map((e) =>
            `<span class="ref causality">${escapeHtml(e)}</span>`
          ).join(" ")
        }</div>`
        : ""
    }
        ${
      event.causes && event.causes.length > 0
        ? `<div class="event-causality causes"><span class="label">Causes:</span> ${
          event.causes.map((e) =>
            `<span class="ref causality">${escapeHtml(e)}</span>`
          ).join(" ")
        }</div>`
        : ""
    }
      </div>`).join("\n");

    return `<div class="timeline-events event-list">${eventItems}</div>`;
  }

  /**
   * 伏線セクションをレンダリング
   */
  private renderForeshadowings(
    foreshadowings: readonly ForeshadowingSummary[],
  ): string {
    if (foreshadowings.length === 0) {
      return '<p class="empty">No foreshadowings found.</p>';
    }

    // 統計情報
    const stats = this.calculateForeshadowingStats(foreshadowings);
    const statsSection = `
        <div class="foreshadowing-stats">
          <span class="stat">Total: <strong>${stats.total}</strong></span>
          <span class="stat">Planted: <strong>${stats.planted}</strong></span>
          <span class="stat">Resolved: <strong>${stats.resolved}</strong></span>
          <span class="stat">Resolution Rate: <strong>${
      stats.resolutionRate.toFixed(0)
    }%</strong></span>
        </div>`;

    // 伏線カード
    const cards = foreshadowings.map((f) => {
      const resolutionsHtml = this.renderResolutions(f.resolutions);
      const relatedHtml = this.renderRelatedEntities(
        f.relatedCharacters,
        f.relatedSettings,
      );

      return `
        <div class="card foreshadowing-card status-${escapeHtml(f.status)}">
          <h3>${escapeHtml(f.name)}</h3>
          <div class="meta">
            <span class="type">${escapeHtml(f.type)}</span>
            <span class="status">${escapeHtml(f.status)}</span>
            ${
        f.importance
          ? `<span class="importance">${escapeHtml(f.importance)}</span>`
          : ""
      }
            <span class="id">${escapeHtml(f.id)}</span>
          </div>
          <p class="summary">${escapeHtml(f.summary ?? "")}</p>
          <div class="planting-info">
            <span class="label">Planted:</span> ${escapeHtml(f.plantingChapter)}
          </div>
          ${resolutionsHtml}
          ${relatedHtml}
          <div class="file-path">
            <code>${escapeHtml(f.filePath)}</code>
          </div>
        </div>`;
    }).join("\n");

    return `${statsSection}<div class="card-grid">${cards}</div>`;
  }

  /**
   * 伏線の統計情報を計算
   */
  private calculateForeshadowingStats(
    foreshadowings: readonly ForeshadowingSummary[],
  ) {
    const stats = {
      total: foreshadowings.length,
      planted: 0,
      partiallyResolved: 0,
      resolved: 0,
      abandoned: 0,
      resolutionRate: 0,
    };

    for (const f of foreshadowings) {
      switch (f.status) {
        case "planted":
          stats.planted++;
          break;
        case "partially_resolved":
          stats.partiallyResolved++;
          break;
        case "resolved":
          stats.resolved++;
          break;
        case "abandoned":
          stats.abandoned++;
          break;
      }
    }

    if (stats.total > 0) {
      stats.resolutionRate =
        ((stats.resolved + stats.partiallyResolved * 0.5) / stats.total) * 100;
    }

    return stats;
  }

  /**
   * 回収情報をレンダリング
   */
  private renderResolutions(
    resolutions: readonly ResolutionSummary[],
  ): string {
    if (resolutions.length === 0) {
      return "";
    }

    const items = resolutions.map((r) => `
      <div class="resolution-item">
        <span class="chapter">${escapeHtml(r.chapter)}</span>
        <span class="description">${escapeHtml(r.description)}</span>
        <span class="completeness">${(r.completeness * 100).toFixed(0)}%</span>
      </div>`).join("");

    return `<div class="resolution-info">${items}</div>`;
  }

  /**
   * 関連エンティティをレンダリング
   */
  private renderRelatedEntities(
    characters: readonly string[],
    settings: readonly string[],
  ): string {
    if (characters.length === 0 && settings.length === 0) {
      return "";
    }

    const charRefs = characters.map((c) =>
      `<span class="ref character">${escapeHtml(c)}</span>`
    ).join(" ");
    const settingRefs = settings.map((s) =>
      `<span class="ref setting">${escapeHtml(s)}</span>`
    ).join(" ");

    return `
      <div class="related-entities">
        ${
      characters.length > 0
        ? `<div class="related-characters"><span class="label">Characters:</span> ${charRefs}</div>`
        : ""
    }
        ${
      settings.length > 0
        ? `<div class="related-settings"><span class="label">Settings:</span> ${settingRefs}</div>`
        : ""
    }
      </div>`;
  }

  /**
   * 原稿セクションをレンダリング
   */
  private renderManuscripts(manuscripts: readonly ManuscriptSummary[]): string {
    if (manuscripts.length === 0) {
      return '<p class="empty">No manuscripts found.</p>';
    }

    const items = manuscripts.map((ms) => `
        <div class="manuscript-item">
          <div class="manuscript-header">
            <h3>${escapeHtml(ms.title ?? ms.path)}</h3>
            <code class="path">${escapeHtml(ms.path)}</code>
          </div>
          <div class="references">
            <span class="label">References:</span>
            ${this.renderReferences(ms.referencedEntities)}
          </div>
        </div>`).join("\n");

    return `<div class="manuscript-list">${items}</div>`;
  }

  /**
   * エンティティ参照をレンダリング
   */
  private renderReferences(
    refs: readonly {
      id: string;
      kind: string;
      occurrences: number;
      status?: string;
    }[],
  ): string {
    if (refs.length === 0) {
      return '<span class="no-refs">None</span>';
    }

    return refs.map((ref) => {
      // 伏線の場合はステータスクラスを追加
      const statusClass = ref.kind === "foreshadowing" && ref.status
        ? ` ${escapeHtml(ref.status)}`
        : "";
      return `<span class="ref ${escapeHtml(ref.kind)}${statusClass}">${
        escapeHtml(ref.id)
      } (${ref.occurrences})</span>`;
    }).join(" ");
  }

  /**
   * キャラクター関係グラフセクションをレンダリング
   */
  private renderCharacterGraph(
    _characters: readonly CharacterSummary[],
  ): string {
    return `
      <div class="graph-panel">
        <h3>Character Relationships</h3>
        <div id="character-graph" class="graph-canvas"></div>
      </div>`;
  }

  /**
   * タイムライン因果グラフセクションをレンダリング
   */
  private renderTimelineGraph(
    _timelines: readonly TimelineSummary[],
  ): string {
    return `
      <div class="graph-panel">
        <h3>Timeline Causality</h3>
        <div id="timeline-graph" class="graph-canvas"></div>
      </div>`;
  }

  /**
   * 伏線フローグラフセクションをレンダリング
   */
  private renderForeshadowingGraph(
    _foreshadowings: readonly ForeshadowingSummary[],
  ): string {
    return `
      <div class="graph-panel">
        <h3>Foreshadowing Flow</h3>
        <div id="foreshadowing-graph" class="graph-canvas"></div>
      </div>`;
  }

  /**
   * グラフ初期化スクリプトをレンダリング
   */
  /**
   * 整合性チェック結果セクションをレンダリング
   */
  private renderConsistency(issues: readonly ConsistencyIssue[]): string {
    if (issues.length === 0) {
      return '<p class="consistency-ok">整合性に問題はありません</p>';
    }

    const issueItems = issues.map((issue) => `
      <div class="issue-item issue-${escapeHtml(issue.severity)}">
        <div class="issue-header">
          <span class="issue-severity severity-${escapeHtml(issue.severity)}">${
      escapeHtml(issue.severity)
    }</span>
          <span class="issue-type">${escapeHtml(issue.type)}</span>
        </div>
        <p class="issue-message">${escapeHtml(issue.message)}</p>
        ${
      issue.suggestion
        ? `<p class="issue-suggestion">${escapeHtml(issue.suggestion)}</p>`
        : ""
    }
      </div>`).join("\n");

    return `<div class="issue-list">${issueItems}</div>`;
  }

  private renderGraphInitScript(analysis: ProjectAnalysis): string {
    const characterGraphData = buildCharacterGraphFromSummary(
      analysis.characters,
    );
    const timelineGraphData = buildTimelineGraphFromSummary(analysis.timelines);
    const foreshadowingGraphData = buildForeshadowingGraphFromSummary(
      analysis.foreshadowings,
    );

    return `
  <script>
    // グラフ初期化
    document.addEventListener('DOMContentLoaded', function() {
      // キャラクター関係グラフ
      const characterContainer = document.getElementById('character-graph');
      if (characterContainer) {
        const characterData = ${JSON.stringify(characterGraphData)};
        const characterNetwork = new vis.Network(
          characterContainer,
          { nodes: new vis.DataSet(characterData.nodes), edges: new vis.DataSet(characterData.edges) },
          characterData.options || {}
        );
      }

      // タイムライン因果グラフ
      const timelineContainer = document.getElementById('timeline-graph');
      if (timelineContainer) {
        const timelineData = ${JSON.stringify(timelineGraphData)};
        const timelineNetwork = new vis.Network(
          timelineContainer,
          { nodes: new vis.DataSet(timelineData.nodes), edges: new vis.DataSet(timelineData.edges) },
          timelineData.options || {}
        );
      }

      // 伏線フローグラフ
      const foreshadowingContainer = document.getElementById('foreshadowing-graph');
      if (foreshadowingContainer) {
        const foreshadowingData = ${JSON.stringify(foreshadowingGraphData)};
        const foreshadowingNetwork = new vis.Network(
          foreshadowingContainer,
          { nodes: new vis.DataSet(foreshadowingData.nodes), edges: new vis.DataSet(foreshadowingData.edges) },
          foreshadowingData.options || {}
        );
      }
    });
  </script>`;
  }
}

/**
 * HTMLをエスケープ
 */
function escapeHtml(text: string): string {
  return text
    .replace(/&/g, "&amp;")
    .replace(/</g, "&lt;")
    .replace(/>/g, "&gt;")
    .replace(/"/g, "&quot;")
    .replace(/'/g, "&#039;");
}

/**
 * インラインCSS
 */
const CSS_STYLES = `
    :root {
      --primary-color: #3498db;
      --secondary-color: #2ecc71;
      --background-color: #f5f6fa;
      --card-background: #ffffff;
      --text-color: #2c3e50;
      --border-color: #dfe6e9;
      --shadow: 0 2px 4px rgba(0,0,0,0.1);
    }

    * {
      box-sizing: border-box;
      margin: 0;
      padding: 0;
    }

    body {
      font-family: -apple-system, BlinkMacSystemFont, 'Segoe UI', Roboto, Oxygen, Ubuntu, sans-serif;
      background-color: var(--background-color);
      color: var(--text-color);
      line-height: 1.6;
    }

    .container {
      max-width: 1200px;
      margin: 0 auto;
      padding: 2rem;
    }

    header {
      text-align: center;
      margin-bottom: 2rem;
      padding-bottom: 1rem;
      border-bottom: 2px solid var(--primary-color);
    }

    header h1 {
      color: var(--primary-color);
      font-size: 2rem;
    }

    section {
      margin-bottom: 2rem;
    }

    section h2 {
      color: var(--text-color);
      font-size: 1.5rem;
      margin-bottom: 1rem;
      padding-bottom: 0.5rem;
      border-bottom: 1px solid var(--border-color);
    }

    .card-grid {
      display: grid;
      grid-template-columns: repeat(auto-fill, minmax(300px, 1fr));
      gap: 1rem;
    }

    .card {
      background: var(--card-background);
      border-radius: 8px;
      padding: 1.5rem;
      box-shadow: var(--shadow);
      transition: transform 0.2s;
    }

    .card:hover {
      transform: translateY(-2px);
    }

    .card h3 {
      color: var(--primary-color);
      margin-bottom: 0.5rem;
    }

    .card .meta {
      display: flex;
      gap: 0.5rem;
      margin-bottom: 0.5rem;
    }

    .card .role {
      background: var(--secondary-color);
      color: white;
      padding: 0.2rem 0.5rem;
      border-radius: 4px;
      font-size: 0.8rem;
    }

    .card .id {
      background: var(--border-color);
      padding: 0.2rem 0.5rem;
      border-radius: 4px;
      font-size: 0.8rem;
    }

    .card .summary {
      color: #666;
      margin-bottom: 0.5rem;
    }

    .display-names {
      margin-bottom: 0.5rem;
    }

    .display-names .label,
    .references .label {
      font-weight: bold;
      margin-right: 0.5rem;
    }

    .tag {
      background: var(--background-color);
      padding: 0.2rem 0.5rem;
      border-radius: 4px;
      font-size: 0.85rem;
      margin-right: 0.25rem;
    }

    .file-path {
      margin-top: 0.5rem;
    }

    .file-path code {
      background: var(--background-color);
      padding: 0.25rem 0.5rem;
      border-radius: 4px;
      font-size: 0.8rem;
    }

    .timeline-list {
      display: flex;
      flex-direction: column;
      gap: 1.5rem;
    }

    .timeline-card {
      border-left: 4px solid var(--primary-color);
    }

    .timeline-card .scope {
      background: #9b59b6;
      color: white;
      padding: 0.2rem 0.5rem;
      border-radius: 4px;
      font-size: 0.8rem;
    }

    .timeline-card .parent-timeline,
    .timeline-card .related-character {
      margin: 0.5rem 0;
      font-size: 0.9rem;
    }

    .timeline-events {
      margin: 1rem 0;
      padding: 1rem;
      background: var(--background-color);
      border-radius: 8px;
    }

    .timeline-events.empty {
      color: #999;
      font-style: italic;
    }

    .event-list {
      display: flex;
      flex-direction: column;
      gap: 1rem;
    }

    .event-item {
      background: var(--card-background);
      padding: 1rem;
      border-radius: 8px;
      border-left: 3px solid var(--secondary-color);
    }

    .event-header {
      display: flex;
      align-items: center;
      gap: 0.5rem;
      margin-bottom: 0.5rem;
    }

    .event-order {
      background: var(--primary-color);
      color: white;
      padding: 0.2rem 0.5rem;
      border-radius: 50%;
      font-size: 0.8rem;
      font-weight: bold;
      min-width: 1.5rem;
      text-align: center;
    }

    .event-title {
      font-weight: bold;
      color: var(--text-color);
    }

    .event-category {
      background: var(--border-color);
      padding: 0.2rem 0.5rem;
      border-radius: 4px;
      font-size: 0.75rem;
      margin-left: auto;
    }

    .event-summary {
      color: #666;
      font-size: 0.9rem;
      margin-bottom: 0.5rem;
    }

    .event-refs {
      margin: 0.25rem 0;
      font-size: 0.85rem;
    }

    .event-refs .label {
      font-weight: bold;
      margin-right: 0.5rem;
    }

    .event-causality {
      margin: 0.25rem 0;
      font-size: 0.85rem;
    }

    .event-causality .label {
      font-weight: bold;
      margin-right: 0.5rem;
    }

    .ref.chapter {
      background: #fff3e0;
      color: #e65100;
    }

    .ref.causality {
      background: #fce4ec;
      color: #c2185b;
    }

    .manuscript-list {
      display: flex;
      flex-direction: column;
      gap: 1rem;
    }

    .manuscript-item {
      background: var(--card-background);
      border-radius: 8px;
      padding: 1.5rem;
      box-shadow: var(--shadow);
    }

    .manuscript-header {
      display: flex;
      justify-content: space-between;
      align-items: center;
      margin-bottom: 0.5rem;
      flex-wrap: wrap;
      gap: 0.5rem;
    }

    .manuscript-header h3 {
      color: var(--primary-color);
    }

    .manuscript-header .path {
      background: var(--background-color);
      padding: 0.25rem 0.5rem;
      border-radius: 4px;
      font-size: 0.8rem;
    }

    .ref {
      display: inline-block;
      padding: 0.2rem 0.5rem;
      border-radius: 4px;
      font-size: 0.85rem;
      margin-right: 0.25rem;
    }

    .ref.character {
      background: #e3f2fd;
      color: #1565c0;
    }

    .ref.setting {
      background: #e8f5e9;
      color: #2e7d32;
    }

    .ref.foreshadowing {
      background: #fff3e0;
      color: #e65100;
    }

    .ref.foreshadowing.planted {
      background: #fff3e0;
      color: #e65100;
      border-left: 3px solid #e67e22;
    }

    .ref.foreshadowing.partially_resolved {
      background: #fffde7;
      color: #f9a825;
      border-left: 3px solid #f1c40f;
    }

    .ref.foreshadowing.resolved {
      background: #e8f5e9;
      color: #2e7d32;
      border-left: 3px solid #27ae60;
    }

    .ref.foreshadowing.abandoned {
      background: #eceff1;
      color: #607d8b;
      border-left: 3px solid #95a5a6;
    }

    .empty {
      color: #999;
      font-style: italic;
    }

    .no-refs {
      color: #999;
      font-style: italic;
    }

    /* Foreshadowing styles */
    .foreshadowing-stats {
      display: flex;
      gap: 1.5rem;
      margin-bottom: 1rem;
      padding: 1rem;
      background: var(--card-background);
      border-radius: 8px;
      box-shadow: var(--shadow);
    }

    .foreshadowing-stats .stat {
      font-size: 0.9rem;
    }

    .foreshadowing-card .type {
      background: #9b59b6;
      color: white;
      padding: 0.2rem 0.5rem;
      border-radius: 4px;
      font-size: 0.8rem;
    }

    .foreshadowing-card .status {
      padding: 0.2rem 0.5rem;
      border-radius: 4px;
      font-size: 0.8rem;
    }

    .foreshadowing-card .importance {
      background: #f39c12;
      color: white;
      padding: 0.2rem 0.5rem;
      border-radius: 4px;
      font-size: 0.8rem;
    }

    .foreshadowing-card.status-planted {
      border-left: 4px solid #e67e22;
    }

    .foreshadowing-card.status-planted .status {
      background: #e67e22;
      color: white;
    }

    .foreshadowing-card.status-partially_resolved {
      border-left: 4px solid #f1c40f;
    }

    .foreshadowing-card.status-partially_resolved .status {
      background: #f1c40f;
      color: #333;
    }

    .foreshadowing-card.status-resolved {
      border-left: 4px solid #27ae60;
    }

    .foreshadowing-card.status-resolved .status {
      background: #27ae60;
      color: white;
    }

    .foreshadowing-card.status-abandoned {
      border-left: 4px solid #95a5a6;
    }

    .foreshadowing-card.status-abandoned .status {
      background: #95a5a6;
      color: white;
    }

    .planting-info {
      margin: 0.5rem 0;
      font-size: 0.9rem;
    }

    .resolution-info {
      margin: 0.5rem 0;
      padding: 0.5rem;
      background: var(--background-color);
      border-radius: 4px;
    }

    .resolution-item {
      display: flex;
      gap: 0.5rem;
      align-items: center;
      margin-bottom: 0.25rem;
      font-size: 0.85rem;
    }

    .resolution-item .chapter {
      background: #fff3e0;
      color: #e65100;
      padding: 0.1rem 0.3rem;
      border-radius: 3px;
    }

    .resolution-item .completeness {
      background: var(--secondary-color);
      color: white;
      padding: 0.1rem 0.3rem;
      border-radius: 3px;
      font-weight: bold;
    }

    .related-entities {
      margin: 0.5rem 0;
      font-size: 0.85rem;
    }

    .related-characters,
    .related-settings {
      margin-bottom: 0.25rem;
    }

    footer {
      text-align: center;
      margin-top: 2rem;
      padding-top: 1rem;
      border-top: 1px solid var(--border-color);
      color: #999;
      font-size: 0.9rem;
    }
`;

/**
 * グラフ用CSS
 */
const GRAPH_STYLES = `
    /* Graph Styles */
    .graphs {
      margin-bottom: 2rem;
    }

    .graph-container {
      display: grid;
      grid-template-columns: repeat(auto-fit, minmax(400px, 1fr));
      gap: 1.5rem;
    }

    .graph-panel {
      background: var(--card-background);
      border-radius: 8px;
      padding: 1rem;
      box-shadow: var(--shadow);
    }

    .graph-panel h3 {
      color: var(--primary-color);
      margin-bottom: 0.5rem;
      font-size: 1.1rem;
    }

    .graph-canvas {
      width: 100%;
      height: 400px;
      border: 1px solid var(--border-color);
      border-radius: 4px;
      background: #fafafa;
    }

    /* グラフのノードホバー時のカーソル */
    .graph-canvas canvas {
      cursor: pointer;
    }
`;

/**
 * 整合性チェック用CSS
 */
const CONSISTENCY_STYLES = `
    /* Consistency Check Styles */
    .consistency-ok {
      color: #27ae60;
      font-weight: bold;
      padding: 1rem;
      background: #e8f5e9;
      border-radius: 8px;
      text-align: center;
    }

    .issue-list {
      display: flex;
      flex-direction: column;
      gap: 1rem;
    }

    .issue-item {
      background: var(--card-background);
      border-radius: 8px;
      padding: 1rem;
      box-shadow: var(--shadow);
    }

    .issue-warning {
      border-left: 4px solid #f39c12;
    }

    .issue-error {
      border-left: 4px solid #e74c3c;
    }

    .issue-info {
      border-left: 4px solid #3498db;
    }

    .issue-header {
      display: flex;
      gap: 0.5rem;
      margin-bottom: 0.5rem;
    }

    .issue-severity {
      padding: 0.2rem 0.5rem;
      border-radius: 4px;
      font-size: 0.8rem;
      font-weight: bold;
      text-transform: uppercase;
    }

    .severity-warning {
      background: #f39c12;
      color: white;
    }

    .severity-error {
      background: #e74c3c;
      color: white;
    }

    .severity-info {
      background: #3498db;
      color: white;
    }

    .issue-type {
      background: var(--border-color);
      padding: 0.2rem 0.5rem;
      border-radius: 4px;
      font-size: 0.8rem;
    }

    .issue-message {
      color: var(--text-color);
      margin-bottom: 0.5rem;
    }

    .issue-suggestion {
      color: #666;
      font-size: 0.9rem;
      font-style: italic;
    }
`;
