/**
 * rag install-hooks コマンド
 * Process 50: 自動更新システム
 *
 * Git hooksをインストールして自動更新を有効化
 */
import type {
  CommandDescriptor,
  CommandOptionDescriptor,
} from "../../types.ts";

/**
 * フックタイプ
 */
export type HookType = "post-commit" | "pre-push";

/**
 * CLI引数の型
 */
export interface InstallHooksCliOptions {
  force?: boolean;
  hook?: string;
}

/**
 * パース後のオプション
 */
export interface InstallHooksOptions {
  /** 既存フックを上書き */
  force: boolean;
  /** インストールするフックタイプ */
  hookType: HookType;
}

/**
 * rag install-hooks コマンドオプション定義
 */
export const RAG_INSTALL_HOOKS_OPTIONS: readonly CommandOptionDescriptor[] = [
  {
    name: "force",
    summary: "既存フックを上書き",
    type: "boolean",
    defaultValue: false,
  },
  {
    name: "hook",
    summary: "フックタイプ: post-commit | pre-push",
    type: "string",
    defaultValue: "post-commit",
  },
];

/**
 * CLI引数をパース
 */
export function parseInstallHooksOptions(
  args: InstallHooksCliOptions,
): InstallHooksOptions {
  const hookType = (args.hook ?? "post-commit") as HookType;

  return {
    force: args.force ?? false,
    hookType,
  };
}

/**
 * post-commit フックスクリプトを生成
 */
export function generatePostCommitHook(): string {
  return `#!/bin/bash
# .git/hooks/post-commit (storyteller rag)
# Auto-generated by storyteller rag install-hooks

set -e

# 変更されたファイルを取得
CHANGED_FILES=$(git diff-tree --no-commit-id --name-only -r HEAD)

# storyteller関連ファイルの変更を検出
STORY_CHANGES=$(echo "$CHANGED_FILES" | grep -E "^(src/|manuscripts/)" || true)

if [ -n "$STORY_CHANGES" ]; then
    echo "[storyteller] Updating RAG index..."

    # 1. RAGドキュメント生成（インクリメンタル）
    storyteller rag export --output .rag-docs --incremental 2>/dev/null || {
        echo "[storyteller] Warning: rag export failed"
        exit 0
    }

    # 2. digragインデックス更新（オプション）
    if command -v digrag &> /dev/null; then
        digrag build --input .rag-docs --output .rag 2>/dev/null || {
            echo "[storyteller] Warning: digrag build failed"
            exit 0
        }
        echo "[storyteller] RAG index updated successfully"
    else
        echo "[storyteller] RAG documents exported (digrag not installed)"
    fi
fi
`;
}

/**
 * pre-push フックスクリプトを生成
 */
export function generatePrePushHook(): string {
  return `#!/bin/bash
# .git/hooks/pre-push (storyteller rag)
# Auto-generated by storyteller rag install-hooks

set -e

echo "[storyteller] Running RAG validation before push..."

# RAGドキュメントの整合性チェック
storyteller rag export --output .rag-docs --json 2>/dev/null | jq -e '.errors | length == 0' > /dev/null || {
    echo "[storyteller] Error: RAG export has errors. Fix before pushing."
    exit 1
}

echo "[storyteller] RAG validation passed"
`;
}

/**
 * フック生成関数を取得
 */
export function getHookGenerator(
  hookType: HookType,
): () => string {
  switch (hookType) {
    case "post-commit":
      return generatePostCommitHook;
    case "pre-push":
      return generatePrePushHook;
    default:
      return generatePostCommitHook;
  }
}

/**
 * rag install-hooks コマンドディスクリプタ
 */
export const ragInstallHooksCommandDescriptor: CommandDescriptor = {
  name: "install-hooks",
  summary: "Git hooksをインストール",
  description:
    "Git hooksをインストールして、コミット時にRAGドキュメントを自動更新します。",
  options: RAG_INSTALL_HOOKS_OPTIONS,
  examples: [
    {
      command: "storyteller rag install-hooks",
      summary: "post-commitフックをインストール",
    },
    {
      command: "storyteller rag install-hooks --force",
      summary: "既存フックを上書き",
    },
    {
      command: "storyteller rag install-hooks --hook pre-push",
      summary: "pre-pushフックをインストール",
    },
  ],
  handler: {
    name: "rag:install-hooks",
    execute: async () => ({ ok: true, value: {} }),
  },
};
