/**
 * lint install-hooks/uninstall-hooks コマンド
 * Process 30-31: Git hooks実装 (TDD)
 *
 * Git pre-commit hookのインストール/アンインストール
 */
import type {
  CommandContext,
  CommandDescriptor,
  CommandOptionDescriptor,
} from "../../types.ts";

/**
 * CLI引数の型
 */
export interface InstallHooksCliOptions {
  strict?: boolean;
}

/**
 * パース後のオプション
 */
export interface InstallHooksOptions {
  /** strictモード: lint失敗時にコミットを拒否 */
  strict: boolean;
}

/**
 * lint install-hooks コマンドオプション定義
 */
export const LINT_INSTALL_HOOKS_OPTIONS: readonly CommandOptionDescriptor[] = [
  {
    name: "strict",
    summary: "lint失敗時にコミットを拒否",
    type: "boolean",
    defaultValue: false,
  },
];

/**
 * CLI引数をパース
 */
export function parseInstallHooksOptions(
  args: InstallHooksCliOptions,
): InstallHooksOptions {
  return {
    strict: args.strict ?? false,
  };
}

/**
 * pre-commit フックスクリプトを生成
 */
export function generatePreCommitHook(options: InstallHooksOptions): string {
  const strictMode = options.strict
    ? `
if [ $LINT_EXIT_CODE -ne 0 ]; then
    echo "[storyteller] Lint errors found. Commit rejected in strict mode."
    exit 1
fi
`
    : `
# Non-strict mode: show warnings but allow commit
exit 0
`;

  return `#!/bin/sh
# .git/hooks/pre-commit (storyteller lint)
# Auto-generated by storyteller lint install-hooks

set -e

echo "[storyteller] Running lint checks..."

# Run storyteller lint on manuscripts
storyteller lint --dir manuscripts 2>/dev/null || LINT_EXIT_CODE=$?

if [ -z "$LINT_EXIT_CODE" ]; then
    LINT_EXIT_CODE=0
fi

if [ $LINT_EXIT_CODE -ne 0 ]; then
    echo "[storyteller] Lint found issues (exit code: $LINT_EXIT_CODE)"
else
    echo "[storyteller] Lint checks passed"
fi
${strictMode}`;
}

/**
 * lint install-hooks コマンドディスクリプタ
 */
export const lintInstallHooksCommandDescriptor: CommandDescriptor = {
  name: "install-hooks",
  summary: "Git pre-commit hookをインストール",
  description:
    "Git pre-commit hookをインストールして、コミット時にlintチェックを自動実行します。",
  options: LINT_INSTALL_HOOKS_OPTIONS,
  examples: [
    {
      command: "storyteller lint install-hooks",
      summary: "pre-commitフックをインストール（警告のみ）",
    },
    {
      command: "storyteller lint install-hooks --strict",
      summary: "strictモードでインストール（lint失敗時にコミット拒否）",
    },
  ],
  handler: {
    name: "lint:install-hooks",
    execute: async (context: CommandContext) => {
      const options = parseInstallHooksOptions(
        context.args as InstallHooksCliOptions,
      );

      // .git/hooks ディレクトリのパスを取得
      const gitHooksDir = ".git/hooks";
      const hookPath = `${gitHooksDir}/pre-commit`;

      try {
        // .git/hooks ディレクトリの存在確認
        try {
          await Deno.stat(gitHooksDir);
        } catch {
          return {
            ok: false,
            error: {
              code: "GIT_NOT_FOUND",
              message: ".git directory not found. Are you in a git repository?",
            },
          };
        }

        // 既存のフックをチェック
        try {
          const existing = await Deno.readTextFile(hookPath);
          if (
            !existing.includes("storyteller lint") &&
            !existing.includes("# .git/hooks/pre-commit (storyteller lint)")
          ) {
            console.warn(
              `Warning: Existing pre-commit hook found. Backup to ${hookPath}.backup`,
            );
            await Deno.writeTextFile(`${hookPath}.backup`, existing);
          }
        } catch {
          // ファイルが存在しない場合は問題なし
        }

        // フックスクリプトを生成して書き込み
        const script = generatePreCommitHook(options);
        await Deno.writeTextFile(hookPath, script);

        // 実行権限を付与
        await Deno.chmod(hookPath, 0o755);

        const mode = options.strict ? "strict mode" : "warning mode";
        console.log(
          `✓ Git pre-commit hook installed successfully (${mode})`,
        );
        console.log(`  Location: ${hookPath}`);

        return { ok: true, value: { hookPath, mode } };
      } catch (error) {
        return {
          ok: false,
          error: {
            code: "INSTALL_FAILED",
            message: error instanceof Error ? error.message : String(error),
          },
        };
      }
    },
  },
};

/**
 * lint uninstall-hooks コマンドディスクリプタ
 */
export const lintUninstallHooksCommandDescriptor: CommandDescriptor = {
  name: "uninstall-hooks",
  summary: "Git pre-commit hookをアンインストール",
  description: "storytellerが作成したGit pre-commit hookを削除します。",
  options: [],
  examples: [
    {
      command: "storyteller lint uninstall-hooks",
      summary: "pre-commitフックをアンインストール",
    },
  ],
  handler: {
    name: "lint:uninstall-hooks",
    execute: async (_context: CommandContext) => {
      const hookPath = ".git/hooks/pre-commit";

      try {
        // フックファイルの存在確認
        const content = await Deno.readTextFile(hookPath);

        // storytellerが作成したフックかどうか確認
        if (
          !content.includes("storyteller lint") &&
          !content.includes("# .git/hooks/pre-commit (storyteller lint)")
        ) {
          return {
            ok: false,
            error: {
              code: "INVALID_HOOK",
              message:
                "Pre-commit hook exists but was not created by storyteller lint. Refusing to delete.",
            },
          };
        }

        // フックファイルを削除
        await Deno.remove(hookPath);

        console.log("✓ Git pre-commit hook uninstalled successfully");
        console.log(`  Removed: ${hookPath}`);

        return { ok: true, value: { removed: hookPath } };
      } catch (error) {
        if (error instanceof Deno.errors.NotFound) {
          return {
            ok: false,
            error: {
              code: "HOOK_NOT_FOUND",
              message: "Pre-commit hook not found. Nothing to uninstall.",
            },
          };
        }
        return {
          ok: false,
          error: {
            code: "UNINSTALL_FAILED",
            message: error instanceof Error ? error.message : String(error),
          },
        };
      }
    },
  },
};
