package generate

import (
	"fmt"
	"os"
	"path/filepath"
	"strings"

	"github.com/takets/street-storyteller/internal/cli"
)

type Command struct{}

func New() cli.Command { return &Command{} }

func (c *Command) Name() string        { return "generate" }
func (c *Command) Description() string { return "Create a new storyteller project" }
func (c *Command) Usage() string {
	return "storyteller generate --name <name> [--path <dir>] [--template basic|novel|screenplay]"
}

func (c *Command) Handle(cctx cli.CommandContext) int {
	opts, err := parseOptions(cctx.Args)
	if err != nil {
		cctx.Presenter.ShowError(err.Error())
		return 1
	}
	if opts.name == "" {
		cctx.Presenter.ShowError("--name is required")
		return 1
	}
	if opts.templateName == "" {
		opts.templateName = "basic"
	}
	if opts.basePath == "" {
		opts.basePath = cctx.GlobalOpts.Path
	}
	if opts.basePath == "" {
		cwd, err := os.Getwd()
		if err != nil {
			cctx.Presenter.ShowError(err.Error())
			return 1
		}
		opts.basePath = cwd
	}

	projectRoot := filepath.Join(opts.basePath, opts.name)
	if err := createProject(projectRoot, opts.name, opts.templateName); err != nil {
		cctx.Presenter.ShowError(err.Error())
		return 1
	}
	if err := installClaudeSkills(projectRoot); err != nil {
		cctx.Presenter.ShowError(err.Error())
		return 1
	}
	if cctx.GlobalOpts.JSON {
		_ = cctx.Presenter.WriteJSON(struct {
			Path     string `json:"path"`
			Template string `json:"template"`
		}{Path: projectRoot, Template: opts.templateName})
		return 0
	}
	cctx.Presenter.ShowSuccess("generated project: " + projectRoot)
	return 0
}

type options struct {
	name         string
	basePath     string
	templateName string
}

func parseOptions(args []string) (options, error) {
	var opts options
	for i := 0; i < len(args); i++ {
		a := args[i]
		switch {
		case a == "--name":
			if i+1 >= len(args) {
				return opts, fmt.Errorf("--name requires a value")
			}
			opts.name = args[i+1]
			i++
		case strings.HasPrefix(a, "--name="):
			opts.name = strings.TrimPrefix(a, "--name=")
		case a == "--path":
			if i+1 >= len(args) {
				return opts, fmt.Errorf("--path requires a value")
			}
			opts.basePath = args[i+1]
			i++
		case strings.HasPrefix(a, "--path="):
			opts.basePath = strings.TrimPrefix(a, "--path=")
		case a == "--template":
			if i+1 >= len(args) {
				return opts, fmt.Errorf("--template requires a value")
			}
			opts.templateName = args[i+1]
			i++
		case strings.HasPrefix(a, "--template="):
			opts.templateName = strings.TrimPrefix(a, "--template=")
		}
	}
	return opts, nil
}

func createProject(root, name, templateName string) error {
	dirs := []string{
		"src/characters",
		"src/settings",
		"src/chapters",
		"src/plots",
		"src/timelines",
		"src/themes",
		"src/structure",
		"src/purpose",
		"src/foreshadowings",
		"src/subplots",
		"manuscripts",
		"drafts",
		"output",
		"tests",
	}
	for _, d := range dirs {
		if err := os.MkdirAll(filepath.Join(root, d), 0755); err != nil {
			return err
		}
	}
	files := map[string]string{
		".storyteller.json":        fmt.Sprintf("{\n  \"version\": \"1.0.0\",\n  \"project\": {\"name\": %q, \"description\": \"\"}\n}\n", name),
		"story.ts":                 "import type { StoryTeller } from \"@storyteller/storyteller_interface.ts\";\n\nexport const story: Partial<StoryTeller> = {\n  charcters: [],\n  settings: [],\n  chapters: [],\n  plots: [],\n};\n",
		"story.config.ts":          fmt.Sprintf("export default {\n  name: %q,\n  template: %q,\n};\n", name, templateName),
		"README.md":                fmt.Sprintf("# %s\n\nGenerated by storyteller.\n", name),
		"manuscripts/chapter01.md": "# Chapter 1\n\n",
		"drafts/ideas.md":          "# Ideas\n\n",
		"tests/story_test.ts":      "Deno.test(\"story validates\", () => {});\n",
	}
	for rel, body := range files {
		path := filepath.Join(root, rel)
		if err := os.MkdirAll(filepath.Dir(path), 0755); err != nil {
			return err
		}
		if err := os.WriteFile(path, []byte(body), 0644); err != nil {
			return err
		}
	}
	return nil
}
