// Package service hosts application services that consolidate logic shared
// between the CLI and MCP adapters. Each service exposes a minimal,
// adapter-agnostic API so the CLI/MCP layers reduce to thin presentation
// shells.
//
// Why a separate package instead of reusing internal/cli or internal/mcp:
// neither adapter should depend on the other, and the duplicated walk + parse
// logic was the most expensive class of drift to maintain across them.
package service

import (
	"fmt"
	"os"
	"path/filepath"
	"strings"

	"github.com/takets/street-storyteller/internal/meta"
)

// MetaCheckService validates manuscript YAML frontmatter under a directory.
//
// Why depth-1 walk: matches the CLI convention documented in
// internal/cli/modules/meta/check.go — chapters live directly under
// manuscripts/, and recursive walks would also pick up draft notes that are
// not authored manuscripts. The MCP adapter previously walked recursively;
// unifying on depth-1 here is the corrected behavior.
type MetaCheckService struct{}

// MetaCheckResult is the adapter-agnostic return contract.
type MetaCheckResult struct {
	FilesChecked int
}

// NewMetaCheckService returns a stateless service instance.
func NewMetaCheckService() *MetaCheckService { return &MetaCheckService{} }

// Run scans root for *.md files (depth 1), parses each via meta.Parse, and
// returns the count. A non-existent root yields a zero-count result without
// error so callers operating on fresh projects do not need to pre-check.
func (s *MetaCheckService) Run(root string) (MetaCheckResult, error) {
	files, err := collectMarkdown(root)
	if err != nil {
		return MetaCheckResult{}, err
	}
	for _, f := range files {
		data, err := os.ReadFile(f)
		if err != nil {
			return MetaCheckResult{}, fmt.Errorf("read %s: %w", f, err)
		}
		doc, err := meta.Parse(data)
		if err != nil {
			return MetaCheckResult{}, fmt.Errorf("%s: %w", f, err)
		}
		if err := validateDetail(doc, f); err != nil {
			return MetaCheckResult{}, err
		}
	}
	return MetaCheckResult{FilesChecked: len(files)}, nil
}

// ValidDetailTypes lists the allowed values for the "type" field in detail md.
// Why: constraining to known types catches typos early and aligns with the
// LSP entity model. plot_detail was added so plot description / beats md can
// also carry frontmatter generated by `storyteller meta annotate`.
// Exported so adapter layers (CLI annotate) can validate without duplicating.
var ValidDetailTypes = map[string]struct{}{
	"character_detail": {},
	"setting_detail":   {},
	"plot_detail":      {},
}

// IsValidDetailType reports whether t is a recognized detail type.
func IsValidDetailType(t string) bool {
	_, ok := ValidDetailTypes[t]
	return ok
}

// validateDetail enforces required fields for detail md files.
// Manuscript files (Kind=="manuscript") pass through without additional checks
// so the existing validation path is unaffected.
func validateDetail(doc *meta.Document, filePath string) error {
	if doc.Kind() != meta.DocumentKindDetail {
		return nil
	}
	fm := doc.FrontMatter
	if fm.Type == "" {
		return fmt.Errorf("%s: detail markdown requires 'type' field", filePath)
	}
	if _, ok := ValidDetailTypes[fm.Type]; !ok {
		return fmt.Errorf("%s: detail markdown 'type' must be one of: character_detail, setting_detail, plot_detail", filePath)
	}
	if fm.EntityID == "" {
		return fmt.Errorf("%s: detail markdown requires 'entity_id' field", filePath)
	}
	if fm.Field == "" {
		return fmt.Errorf("%s: detail markdown requires 'field' field", filePath)
	}
	return nil
}

func collectMarkdown(dir string) ([]string, error) {
	entries, err := os.ReadDir(dir)
	if err != nil {
		if os.IsNotExist(err) {
			return nil, nil
		}
		return nil, fmt.Errorf("read dir %s: %w", dir, err)
	}
	out := []string{}
	for _, e := range entries {
		if e.IsDir() {
			continue
		}
		if !strings.HasSuffix(e.Name(), ".md") {
			continue
		}
		out = append(out, filepath.Join(dir, e.Name()))
	}
	return out, nil
}
