#!/usr/bin/env sh
set -eu

root=$(CDPATH= cd -- "$(dirname -- "$0")/.." && pwd)
out="$root/docs/go-migration-inventory.md"

count_ts() {
  find "$root/$1" -type f -name '*.ts' | wc -l | tr -d ' '
}

cat > "$out" <<EOF
# Go Migration Inventory

Generated by \`scripts/inventory.sh\`.

## Coverage

| Module Root | Files | Imports From | Importers | Priority | Target Process |
| --- | ---: | --- | --- | --- | --- |
| \`src/cli/modules\` | retired | Go CLI modules | cmd/storyteller | done | 04 |
| \`src/lsp\` | retired | internal/lsp | cli/lsp, mcp/tools | done | 05 |
| \`src/mcp\` | retired | internal/mcp | cli/mcp | done | 06 |
| \`src/rag\` | retired | retired | none | none | 07 skipped |

## Dependency Groups

| Group | Scope | Target |
| --- | --- | --- |
| A | help, version, view primitives | Process 04 |
| B | generate, meta, element, update | Process 04 |
| C | lsp server/providers/diagnostics | Process 05 |
| D | mcp server/tools/resources/prompts | Process 06 |
| E | rag export/update/hooks | retired |
| F | textlint adapter | Process 08 |

## Dependency Graph

\`\`\`mermaid
flowchart TD
  CLI[src/cli/modules] --> Project[internal/project]
  CLI --> Service[internal/service]
  CLI --> LSP[src/lsp]
  CLI --> MCP[src/mcp]
  LSP --> Detect[internal/detect]
  LSP --> Project
  MCP --> Service
  MCP --> Project
\`\`\`

## Cycle check

No TypeScript runtime dependency cycle blocks the Go migration plan. The target
order remains: 03 -> 04 -> {05,06,08}; Process 07 is skipped because RAG is retired.
EOF

printf '%s\n' "$out"
